name: Build and Publish Docker Images after create release tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-push-docker-image:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    name: Build Docker image and push to repositories with version tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # Help to generate the labels for ko
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/cloudflare_exporter
          # generate Docker tags based on the following events/attributes
          tags: type=ref,event=tag
        
      # TODO, enable dockerhub again when I'm done testing localy
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: "go.mod"
          cache: false


      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9
        with:
          version: v0.18.0
      - name: Build and push
        id: publish-image
        env:
          IMAGE_VERSION: ${{ github.ref_name }}
          KO_DOCKER_REPO: "ghcr.io/${{ github.repository }}"
        run: |
          # Build multi-platform with labels from docker/metadata-action
          # Convert multiline labels output to --image-label args
          LABELS=""
          while IFS= read -r label; do
            if [ -n "$label" ]; then
              LABELS="$LABELS --image-label $label"
            fi
          done <<< "${{ steps.meta.outputs.labels }}"

          ko build . --sbom=none --image-refs ./image-digest --bare --platform linux/arm64,linux/amd64 -t ${IMAGE_VERSION} $LABELS

          # Extract image digest from ko output (removes image name, keeps only sha256:... part)
          IMAGE_REF=$(cat ./image-digest)
          IMAGE_DIGEST=$(echo "$IMAGE_REF" | sed 's/.*@//')
          echo "digest=${IMAGE_DIGEST}" >> $GITHUB_OUTPUT
          echo "image-ref=${IMAGE_REF}" >> $GITHUB_OUTPUT

      - name: Attest
        uses: actions/attest-build-provenance@v2
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.publish-image.outputs.digest }}
          push-to-registry: true
